uint8 epsmethod          #方向盘使能位
int16 epsangle           #放向盘角度
uint8 espmethod          #esp使能位
float32 escbrakepress      #刹车压力
uint8 gaspedal           #油门开度
uint8 sysstatus          #系统状态
float32 speed            #车速
uint8 lights             #灯光
uint8 turnLight
uint8 gear
uint8 epb
uint8 door
uint8 isvalid            #有效位
int64 timestamp          #时间戳
uint8 sendsuccess
uint8 brakepedal
uint8 warning
int16 error
uint8 battery
uint8 controlover
int32 steerspeed
int32 accelpos
int32 breakflag
int32 breakpos 
int32 yaw 
int32 mil 
float32 soc  
float32 batvol 
int32 acc 
int32 oilperhour  
int32 oilhundredkmconsume  
int32 oilconsume  
int32 autoctrlsig 
float32 totalvoltage 
float32 totalcurrent
int32 motorspeed 
int32 motortorque 
uint8   wireControlStatus # 线控状态，0关闭，1打开
uint8   blinkerStatus     # 双闪状态，0关闭，1打开
float32 accx              # 纵向加速度 m/s2
float32 gaspedalcar       # 油门踏板开度


