int64 timeStamp #时间戳-毫秒 发布跟踪预测轨迹信息 20220913
point3d trajectoryPoint   #轨迹点坐标XYZ 20220913
float64 lon          #纬度    #20220914
float64 lat          #经度
float64 alt          #高度
float32 roll    #N 20220920
float32 pitch   #E
float32 heading #D
float32 relavx		
float32 relavy
float32 absvx       #m/s
float32 absvy       #m/s
float32 s           #m
float32 l           #m
float32 speeds      #m/s
float32 speedl      #m/s