float32 timestep      #时间步长-0.1s
float32 x             #x-carBackRFU-m
float32 y             #y-carBackRFU-m
float32 z             #z-carBackRFU-m
float64 longtitude    #纬度    #20220914
float64 latitude      #经度
float64 altitude      #高度
float32 rollRad                #横滚角 rad   
float32 pitchRad               #俯仰角 rad        
float32 azimuth                #航向角 rad
float32 relavx        #相对速度-m/s
float32 relavy        #相对速度-m/s
float32 absvx       #绝对速度-m/s
float32 absvy       #绝对速度-m/s
float32 heading       #自车RFU坐标Y轴正方向顺时针0-2pi,rad
float32 s           #m
float32 l           #m
float32 speeds      #m/s
float32 speedl      #m/s
