Header header
float64 cur_gear                        # 实际档位:1P2R3N4D
float64 steering_wheel_angle            # 实际方向盘转角
float64 steering_wheel_rot_dir          # 实际方向盘角速度方向
float64 steering_wheel_rot_spd          # 实际方向盘角速度值
float64 acc_ped1                        # 加速踏板第一路
float64 acc_ped2                        # 加速踏板第二路
int16   Automode                        # 自动驾驶状态标志位，0人工，1自动
int16   flag_can_read_success           # canread成功标志位